# Generated by Django 5.2.7 on 2026-01-15 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='calender_classessID',
            field=models.ForeignKey(db_column='calender_classessID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.classess'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_courseID',
            field=models.ForeignKey(db_column='calender_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_levelID',
            field=models.ForeignKey(db_column='calender_levelID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_registerID',
            field=models.ForeignKey(db_column='check_registerID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.register'),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_studentID',
            field=models.ForeignKey(db_column='check_studentID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.student'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='province_id',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='WebApp.provinces'),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_courseID',
            field=models.ForeignKey(db_column='classess_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_levelID',
            field=models.ForeignKey(db_column='classess_levelID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_courseID',
            field=models.ForeignKey(db_column='inventory_courseID', default=0, on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_levelID',
            field=models.ForeignKey(db_column='inventory_levelID', default=0, on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
        migrations.AlterField(
            model_name='payed',
            name='payed_courseID',
            field=models.ForeignKey(db_column='payed_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='payed',
            name='payed_levelID',
            field=models.ForeignKey(db_column='payed_levelID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
        migrations.AlterField(
            model_name='payed',
            name='payed_registerID',
            field=models.ForeignKey(db_column='payed_registerID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.register'),
        ),
        migrations.AlterField(
            model_name='payed',
            name='payed_studentID',
            field=models.ForeignKey(db_column='payed_studentID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.student'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user_ID',
            field=models.ForeignKey(db_column='profile_user_ID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.user'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorys2ID',
            field=models.ForeignKey(db_column='registerInventorys2ID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID2', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorys3ID',
            field=models.ForeignKey(db_column='registerInventorys3ID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID3', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorysID',
            field=models.ForeignKey(db_column='registerInventorysID', default=0, on_delete=django.db.models.deletion.CASCADE, to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_classessID',
            field=models.ForeignKey(db_column='register_classessID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.classess'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_courseID',
            field=models.ForeignKey(db_column='register_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_levelID',
            field=models.ForeignKey(db_column='register_levelID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_studentID',
            field=models.ForeignKey(db_column='register_studentID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.student'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_courseID',
            field=models.ForeignKey(db_column='score_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_studentID',
            field=models.ForeignKey(db_column='score_studentID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.student'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuition_courseID',
            field=models.ForeignKey(db_column='tuition_courseID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuition_levelID',
            field=models.ForeignKey(db_column='tuition_levelID', on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
    ]
