# Generated by Django 5.2.7 on 2026-01-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_calender_calender_classessid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='check_bankName',
            new_name='chcekBankname',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_bankFork',
            new_name='checkBankFork',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_bankForkcode',
            new_name='checkBankForkcode',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_backFullname',
            new_name='checkBankFullname',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_createTime',
            new_name='checkCreatetime',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_detail',
            new_name='checkDetail',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_lastUpdate',
            new_name='checkLastupdate',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_bankNumber',
            new_name='checkNumber',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_payDate',
            new_name='checkPayDate',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_price',
            new_name='checkPrice',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='check_status',
            new_name='checkStatus',
        ),
    ]
