# Generated by Django 5.2.7 on 2026-01-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_rename_check_bankname_check_chcekbankname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='chcekBankname',
            new_name='checkBankname',
        ),
    ]
