# Generated by Django 5.2.7 on 2026-01-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_rename_chcekbankname_check_checkbankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checkLastupdate',
            field=models.DateTimeField(null=True),
        ),
    ]
