# Generated by Django 5.2.7 on 2026-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_check_checklastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='studentMadarmobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentPedarmobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_day7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_endDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='calender_startDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkBankFork',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkBankForkcode',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkBankFullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkBankname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkCreatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkDetail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkPayDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_createTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_endDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_examDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_lastUpdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_sex',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_startDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classess_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costCaption',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costLastUpdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costPicture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='costPrice',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='costcategory',
            name='costcategoryLastupdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='costcategory',
            name='costcategoryParrent',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseCreateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryCreatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryStatus',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryTitle',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelCreatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderAgentcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDiscountCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderIn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPackageName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderPaytime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payed',
            name='payedCreatedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_bankname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_cardnumber',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_facebook',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_google',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_instagram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_link',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_sheba',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_tell',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_twitter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerCreateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerDiscount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerIsdiscount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerMustpay',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerPayed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerShahrieh',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerpayPrice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreCardnumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreCreateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreDays',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreHour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreRoom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreTeacherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentAddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentCity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentCreatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentLastUpdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentShenasnameh',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentSodoor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentTell',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studenttavalod',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherAddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherCity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherShenasnameh',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherSodoor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherTavalod',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherTell',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitionCreateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitionLastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_active_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastlogin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_registerdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
