# Generated by Django 5.2.7 on 2026-01-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_inventory_id_student_studentmadarmobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classess',
            old_name='classess_createTime',
            new_name='classessCreateTime',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_endDate',
            new_name='classessEndDate',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_examDate',
            new_name='classessExamDate',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_lastUpdate',
            new_name='classessLastUpdate',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_sex',
            new_name='classessSex',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_startDate',
            new_name='classessStartDate',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_status',
            new_name='classessStatus',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_title',
            new_name='classessTitle',
        ),
        migrations.RenameField(
            model_name='classess',
            old_name='classess_type',
            new_name='classessType',
        ),
    ]
