# Generated by Django 5.2.7 on 2026-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_rename_classess_createtime_classess_classesscreatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='regusterPaymethod',
            field=models.IntegerField(default=1),
        ),
    ]
