# Generated by Django 5.2.7 on 2026-01-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_register_regusterpaymethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='regusterPaymethod',
            new_name='registerPaymethod',
        ),
    ]
