# Generated by Django 5.2.7 on 2026-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_rename_regusterpaymethod_register_registerpaymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerPayment',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
