# Generated by Django 5.2.7 on 2026-01-15 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_alter_register_registerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_levelID',
            field=models.ForeignKey(db_column='score_levelID', default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
            preserve_default=False,
        ),
    ]
