# Generated by Django 5.2.7 on 2026-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_score_score_levelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payed',
            name='payedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
