# Generated by Django 5.2.7 on 2026-01-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_alter_inventory_inventory_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_courseID',
            field=models.ForeignKey(db_column='inventory_courseID', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.course'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_levelID',
            field=models.ForeignKey(db_column='inventory_levelID', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.level'),
        ),
    ]
