# Generated by Django 5.2.7 on 2026-01-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_inventory_inventory_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerInventorys2ID',
            field=models.ForeignKey(db_column='registerInventorys2ID', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID2', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorys3ID',
            field=models.ForeignKey(db_column='registerInventorys3ID', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID3', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorysID',
            field=models.ForeignKey(db_column='registerInventorysID', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.inventory'),
        ),
    ]
