# Generated by Django 5.2.7 on 2026-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_alter_register_registerinventorys2id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerInventorys2price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorys3price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorysprice',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
