# Generated by Django 5.2.7 on 2026-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_alter_register_registerinventorys2price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
