# Generated by Django 5.2.7 on 2026-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_alter_register_registerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
