# Generated by Django 5.2.7 on 2026-01-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_alter_register_registercreatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerInventorys2ID',
            field=models.ForeignKey(db_column='registerInventorys2ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID2', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorys3ID',
            field=models.ForeignKey(db_column='registerInventorys3ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID3', to='WebApp.inventory'),
        ),
        migrations.AlterField(
            model_name='register',
            name='registerInventorysID',
            field=models.ForeignKey(db_column='registerInventorysID', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.inventory'),
        ),
    ]
