# Generated by Django 5.2.7 on 2026-01-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_alter_register_registerinventorys2id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_classessID',
            field=models.ForeignKey(db_column='register_classessID', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.classess'),
        ),
    ]
