# Generated by Django 5.2.7 on 2026-01-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_alter_register_register_classessid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
