# Generated by Django 5.2.7 on 2026-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventoryCreatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
