# Generated by Django 5.2.7 on 2026-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_alter_inventory_inventorycreatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
