# Generated by Django 5.2.7 on 2026-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_alter_course_coursecreatetime_alter_course_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseStatus',
            field=models.IntegerField(default=0),
        ),
    ]
