# Generated by Django 5.2.7 on 2026-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_alter_course_coursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='levelCreatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
