# Generated by Django 5.2.7 on 2026-01-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0026_alter_level_levelcreatetime_alter_level_levelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='tuitionCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
