# Generated by Django 5.2.7 on 2026-01-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_alter_tuition_tuitioncreatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
