# Generated by Django 5.2.7 on 2026-01-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='calenderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classessCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classessCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='classess',
            name='classessID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
