# Generated by Django 5.2.7 on 2026-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_alter_calender_calenderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scoreID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
