from django.urls import path
from . import views

urlpatterns = [
    path("admin/", views.AdminPage.as_view(), name="admin"),
    path("register/", views.Register.as_view(), name="register"),
    path("register/addpay/<int:student_id>", views.Admin_addPay.as_view(), name="addpay"),
    path("classes/", views.Classes.as_view(), name="classes"),
    path("classeslist/<int:classID>", views.ClassList.as_view(), name="classlist"),
    path("register/classes/addstudent/<int:classID>", views.Class_alterstudent.as_view(), name="addstudent"),
    path("calender/", views.CalenderList.as_view(), name="calenderlist"),
    path("register/score", views.ScoreList.as_view(), name="scorelist"),
    path("student/add", views.AddStudent.as_view(), name="studentadd"),
    path("student/index", views.StudentList.as_view(), name="studentlist"),
    path("teacher/index", views.TeacherList.as_view(), name="teacherlist"),
    path("teacher/add", views.Addteacher.as_view(), name="teacheradd"),
    path("inventory/index", views.InventoryList.as_view(), name="inventorylist"),
    path("course/index", views.CourseList.as_view(), name="courselist"),
    path("course/level", views.levelList.as_view(), name="levellist"),
    path("course/tuition", views.TuitionList.as_view(), name="tuitionlist"),
    path("register/check/index", views.checkList.as_view(), name="checklist"),
    path("inventory/copyall", views.InventoryCopy.as_view(), name="inventorycopy"),
    path("reports/index", views.ReportIndex.as_view(), name="reportindex"),
    path("reports/get/<int:courseID>", views.ReportGet.as_view(), name="reportget"),
    path("reports/levelindex", views.levelIndex.as_view(), name="levelindex"),
    path("reports/levels/<int:courseID>/<int:levelID>", views.levelTable.as_view(), name="leveltable"),
    path("student/update/<int:studentID>", views.StudentUpdate.as_view(), name="studentupdate"),
    path("teacher/update/<int:teacherID>", views.TeacherUpdate.as_view(), name="teacherupdate"),
    path("course/level/update/<int:levelID>", views.LevelUpdate.as_view(), name="levelupdate"),
    path("course/tuition/update/<int:tuitionID>", views.TuitionUpdate.as_view(), name="tuitionupdate"),
    path("inventory/update/<int:inventoryID>", views.InventoryUpdate.as_view(), name="inventoryupdate"),
    path("profile", views.Profile.as_view(), name="profile"),
    path("register/add", views.RegisterAdd.as_view(), name="registeradd"),
    path("register/classes/add", views.ClassAdd.as_view(), name="classadd"),
    path("register/calender/add", views.CalenderAdd.as_view(), name="calenderadd"),
    path("register/score/add", views.ScoreAdd.as_view(), name="scoreadd"),
    path("register/update/<int:registerID>", views.RegisterUpdate.as_view(), name="registerupdate"),
    path("register/classes/update/<int:classID>", views.ClassUpdate.as_view(), name="classupdate") 
]
